# Generated by Django 3.0.3 on 2020-02-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_auto_20200207_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeanutButter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('picture_address', models.CharField(max_length=500)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
